name = hello_lade
version = "1.0.0"
description = "Test package for lade"
license = "MIT"
authors = "Pik6C"
repository = "https://lade-package-manager/hello_lade"
download = "https://github.com/lade-package-manager/hello_lade/download/release/1.0/test-pkg.ladepkg"
