name = "hello_lade"
version = "1.0.0"
description = "test package for lade"
license = "MIT"
authors = ["Pik6C"]
dependencies = ["hello_knife"]
repository = "https://github.com/lade-package-manager/lade"
download = ""
